title: Room.401
email: eternalglee@naver.com
description:
  그런 사악함 앞에서 중립은 공모와 다름 없어요.
baseurl: ''
url: 'https://eternalglee.github.io/'
timezone: Asia/Seoul

repository: 2023_glee/eternalglee.github.io

permalink: /:year/:month/:day/:title/

excerpt_separator: <!--more-->

markdown: kramdown

krandown:
  input: GFM
  highlighter: rouge

plugins:
  - jekyll-paginate

paginate: 5
paginate_path: '/page/:num/'

collections:
  authors:
    output: true
    permalink: /authors/:path/
  tags:
    output: true
    permalink: /tags/:path/

defaults:
  - scope:
      path: ''
      type: authors
    values:
      layout: author
  - scope:
      path: ''
      type: tags
    values:
      layout: tag

exclude: [README.md, Gemfile, Gemfile.lock]

disqus_url: <https://eternalglee.github.io/>
disqus_id: <room-401>

keep_files: [assets, files]
github: [metadata]
# iolo's custom
author: eternalglee@naver.com
image: '/assets/images/default_blog_cover.jpg'
asset_url: /assets
#asset_url: //meta-kage.kakaocdn.net/dn/osa/blog/assets
#asset_url: //t1.daumcdn.net/osa/blog/assets
github_url:
  username: eternalglee


